name: Waka Readme

on:
  schedule:
    - cron: '0 */1 * * *' # Runs every 1 hours
  workflow_dispatch: # Allows manual runs

jobs:
      update-readme:
        name: Update Readme with Waka Stats
        runs-on: ubuntu-latest
        steps:
          - uses: anmol098/waka-readme-stats@master
            with:
              WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SHOW_TOTAL_CODE_TIME: "true" 
              SHOW_TITLE: "true"
